[global]
   workgroup = WORKGROUP
   netbios name = SSMS-STORAGE
   server string = Server Storage Management System

   security = user
   passdb backend = tdbsam
   map to guest = never
   restrict anonymous = 2

   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d

   server role = standalone server
   obey pam restrictions = yes
   unix password sync = no
   pam password change = no

   usershare allow guests = no
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[homes]
   comment = Personal Storage
   browseable = no
   read only = no
   valid users = %S
   create mask = 0600
   directory mask = 0700
   force create mode = 0600
   force directory mode = 0700
   inherit permissions = no
